name: 'platformatic-runtime-demo'

services:
  postgresql:
    image: arm64v8/postgres:15-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: arm64v8/redis:7.0.10-alpine
    volumes: 
      - redis-data:/data
    ports:
      - 6379:6379

volumes:
  postgres-data:
  redis-data:
